### ISSUE TITLE
Instantiation on every update

### ISSUE THREAD

**Issue by bmfs** [ciscoheat/SnakeDCI#1]
This probably has nothing to do with DCI and it relates more with the actual implementation.

For example in https://github.com/ciscoheat/SnakeDCI/blob/master/src/contexts/Movement.hx#L117
on every frame update, it will create a new instance o Collision.
The same happens with the Movement context.

Would it be ok to only have an instance of the context and reuse it on each frame update?

**Comment by ciscoheat** [comment]
Hello! It has to with DCI actually, since reusing the context could create a confusion about which objects are bound to which Roles. As said in [this FAQ question](http://fulloo.info/doku.php?id=can_i_rebind_roles_to_objects_multiple_times_over_the_lifetime_of_a_context_object):

> I have a context with two accounts and I want to transfer money between the two. Would I want during the execution of said context that one of the accounts is changed?

The answer is probably no, and as long as there aren't any obvious performance problems, creating a new Context like I do is a way to reduce surprises. 

For this simple game, it could probably work to have those contexts long-running instead as you suggest, since the Roles are the same through the whole game. But it's hard to ensure that, so I'm keeping things simple and creating new Contexts as we go. The GC should be pretty fast in cleaning up the previous Context anyway. :)
